variables:
  GIT_STRATEGY: fetch

stages:
  - build-and-push
  - deploy

build-and-push:
  stage: build-and-push
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login --username json_key --password-stdin cr.yandex < $key
    - docker build -t "cloud-hw-3:$CI_COMMIT_TAG" --build-arg app_version="$CI_COMMIT_TAG" src/
    - docker tag "cloud-hw-3:$CI_COMMIT_TAG" $CI_REGISRTY/cloud-hw-3:$CI_COMMIT_TAG
    - docker push $CI_REGISRTY/cloud-hw-3:$CI_COMMIT_TAG
    - docker rmi $CI_REGISRTY/cloud-hw-3:$CI_COMMIT_TAG
  rules:
   - if: '$CI_COMMIT_TAG != null'
  tags:
    - docker

deploy-production:
  stage: deploy
  image: willhallonline/ansible:latest
  script:
    - mkdir secret
    - echo "$ANSIBLE_SSHKEY" > secret/ansible.key
    - chmod 400 secret/ansible.key
    - ansible --version
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook --private-key secret/ansible.key --user ansible_deploy --inventory $INVENTORY *.yml --extra-vars "git_tag=$CI_COMMIT_TAG"
  rules:
    - if: '$CI_COMMIT_TAG != null'
  when: manual
  tags:
    - docker
